<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AdminTicketController extends Controller
{
    public function index()
    {
        $tickets = [
            (object)[
                'id' => 'TK000001',
                'userid' => 'STUD000001',
                'title' => 'Fan Not Working',
                'category' => 'Room Facilities',
                'description' => 'Fan stops functioning',
                'location' => 'M04 Saujana 04-28B',
                'date' => '05/01/2025',
                'status' => 'Completed',
                'resolved_date' => '06/01/2025',
            ],
            (object)[
                'id' => 'TK000002',
                'userid' => 'STUD000001',
                'title' => 'Light Flickering',
                'category' => 'Electrical & Lighting',
                'description' => 'Main light flickers occasionally.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '11/01/2025',
                'status' => 'Completed',
                'resolved_date' => '13/02/2025',
            ],
            (object)[
                'id' => 'TK000003',
                'userid' => 'STUD000002',
                'title' => 'Slow Wi-Fi Speed',
                'category' => 'Internet Connection',
                'description' => 'Wi-Fi unusually slow at night.',
                'location' => 'M03 Saujana 03-56A',
                'date' => '16/01/2025',
                'status' => 'Cancel',
                'comment' => 'Ticket cancelled as the problem has been resolved.',
                'resolved_date' => '18/01/2025',
            ],
            (object)[
                'id' => 'TK000004',
                'userid' => 'STUD000003',
                'title' => 'Dirty Pantry Area',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Pantry not clean.',
                'location' => 'M03 Saujana Pantry Level 4',
                'date' => '18/01/2025',
                'status' => 'Completed',
                'resolved_date' => '19/01/2025',
            ],
            (object)[
                'id' => 'TK000005',
                'userid' => 'STUD000001',
                'title' => 'Clogged Toilet',
                'category' => 'Toilet & Plumbing',
                'description' => 'Toilet bowl clogged.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '21/01/2025',
                'status' => 'Cancel',
                'comment' => 'Ticket cancelled as the problem has been resolved.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000006',
                'userid' => 'STUD000004',
                'title' => 'Broken Study Table',
                'category' => 'Room Facilities',
                'description' => 'Table leg broken.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '25/01/2025',
                'status' => 'Completed',
                'resolved_date' => '26/01/2025',
            ],
            (object)[
                'id' => 'TK000007',
                'userid' => 'STUD000001',
                'title' => 'Power Socket Not Working',
                'category' => 'Electrical & Lighting',
                'description' => 'Socket suddenly stopped functioning.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '30/01/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000008',
                'userid' => 'STUD000005',
                'title' => 'Frequent Wi-Fi Disconnection',
                'category' => 'Internet Connection',
                'description' => 'Wi-Fi disconnects frequently.',
                'location' => 'M04 Saujana 06-32B',
                'date' => '02/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000009',
                'userid' => 'STUD000006',
                'title' => 'Dusty Corridor',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Corridor not cleaned for days.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '05/02/2025',
                'status' => 'Completed',
                'resolved_date' => '06/02/2025',
            ],
            (object)[
            'id' => 'TK000010',
            'userid' => 'STUD000002',
            'title' => 'Air Conditioner Leaking',
            'category' => 'Room Facilities',
            'description' => 'Water dripping from AC.',
            'location' => 'M03 Saujana 03-56A',
            'date' => '10/02/2025',
            'status' => 'Completed',
            'resolved_date' => '11/02/2025',
            ],
            (object)[
                'id' => 'TK000011',
                'userid' => 'STUD000007',
                'title' => 'Room Light Not Turning On',
                'category' => 'Electrical & Lighting',
                'description' => 'Switch responds but no light.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '12/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000012',
                'userid' => 'STUD000004',
                'title' => 'Intermittent Wi-Fi Drop',
                'category' => 'Internet Connection',
                'description' => 'Disconnects for a few minutes.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '13/02/2025',
                'status' => 'Completed',
                'resolved_date' => '14/02/2025',
            ],
            (object)[
                'id' => 'TK000013',
                'userid' => 'STUD000008',
                'title' => 'Unclean Washroom',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Washroom floor dirty.',
                'location' => 'M03 Saujana 02-12A',
                'date' => '14/02/2025',
                'status' => 'Completed',
                'resolved_date' => '15/02/2025',
            ],
            (object)[
                'id' => 'TK000014',
                'userid' => 'STUD000009',
                'title' => 'Pipe Leakage',
                'category' => 'Toilet & Plumbing',
                'description' => 'Water leaking below sink.',
                'location' => 'M04 Saujana 01-08A',
                'date' => '15/02/2025',
                'status' => 'Cancel',
                'comment' => 'Issue resolved by student.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000015',
                'userid' => 'STUD000002',
                'title' => 'Broken Door Lock',
                'category' => 'Room Facilities',
                'description' => 'Door cannot lock properly.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '17/02/2025',
                'status' => 'Completed',
                'resolved_date' => '18/02/2025',
            ],
            (object)[
                'id' => 'TK000016',
                'userid' => 'STUD000006',
                'title' => 'Corridor Lights Off',
                'category' => 'Electrical & Lighting',
                'description' => 'Whole corridor lights not working.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '18/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000017',
                'userid' => 'STUD000007',
                'title' => 'No Water Supply',
                'category' => 'Toilet & Plumbing',
                'description' => 'Water suddenly stops.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '20/02/2025',
                'status' => 'Completed',
                'resolved_date' => '20/02/2025',
            ],
            (object)[
                'id' => 'TK000018',
                'userid' => 'STUD000003',
                'title' => 'Dirty Laundry Area',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Trash not cleaned for days.',
                'location' => 'M03 Saujana Laundry Level 2',
                'date' => '21/02/2025',
                'status' => 'Completed',
                'resolved_date' => '22/02/2025',
            ],
            (object)[
                'id' => 'TK000019',
                'userid' => 'STUD000005',
                'title' => 'Poor Wi-Fi Signal Strength',
                'category' => 'Internet Connection',
                'description' => 'Signal very weak.',
                'location' => 'M04 Saujana 06-32B',
                'date' => '23/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000020',
                'userid' => 'STUD000002',
                'title' => 'Broken Chair',
                'category' => 'Room Facilities',
                'description' => 'Chair leg snapped.',
                'location' => 'M03 Saujana 03-56A',
                'date' => '25/02/2025',
                'status' => 'Completed',
                'resolved_date' => '26/02/2025',
            ],
            (object)[
                'id' => 'TK000021',
                'userid' => 'STUD000004',
                'title' => 'Light Buzzing Noise',
                'category' => 'Electrical & Lighting',
                'description' => 'Buzzing from ceiling light.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '26/02/2025',
                'status' => 'Completed',
                'resolved_date' => '26/02/2025',
            ],
            (object)[
                'id' => 'TK000022',
                'userid' => 'STUD000009',
                'title' => 'Unpleasant Odour in Toilet',
                'category' => 'Toilet & Plumbing',
                'description' => 'Smell for hours.',
                'location' => 'M04 Saujana 01-08C',
                'date' => '28/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000023',
                'userid' => 'STUD000008',
                'title' => 'Wet Corridor',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Water spilled, not cleaned.',
                'location' => 'M03 Saujana Corridor Level 3',
                'date' => '01/03/2025',
                'status' => 'Completed',
                'resolved_date' => '02/03/2025',
            ],
            (object)[
                'id' => 'TK000024',
                'userid' => 'STUD000010',
                'title' => 'Wi-Fi Authentication Error',
                'category' => 'Internet Connection',
                'description' => 'Cannot connect to Wi-Fi.',
                'location' => 'M04 Saujana 08-11A',
                'date' => '03/03/2025',
                'status' => 'Cancel',
                'comment' => 'Duplicate ticket.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000025',
                'userid' => 'STUD000006',
                'title' => 'Dusty Cupboard',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Cupboard full of dust.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '04/03/2025',
                'status' => 'Completed',
                'resolved_date' => '05/03/2025',
            ],
            (object)[
                'id' => 'TK000026',
                'userid' => 'STUD000003',
                'title' => 'Loose Water Tap',
                'category' => 'Toilet & Plumbing',
                'description' => 'Tap wiggles when used.',
                'location' => 'M03 Saujana 04-27A',
                'date' => '05/03/2025',
                'status' => 'Completed',
                'resolved_date' => '06/03/2025',
            ],
            (object)[
                'id' => 'TK000027',
                'userid' => 'STUD000010',
                'title' => 'Wall Paint Peeling Off',
                'category' => 'Room Facilities',
                'description' => 'Paint falling from wall.',
                'location' => 'M04 Saujana 08-11A',
                'date' => '07/03/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000028',
                'userid' => 'STUD000007',
                'title' => 'Light Switch Hot',
                'category' => 'Electrical & Lighting',
                'description' => 'Switch becomes hot.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '08/03/2025',
                'status' => 'Completed',
                'resolved_date' => '09/03/2025',
            ],
            (object)[
                'id' => 'TK000029',
                'userid' => 'STUD000010',
                'title' => 'Dirty Pantry Sink',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Sink full of leftover food.',
                'location' => 'M03 Saujana Pantry Level 2',
                'date' => '10/03/2025',
                'status' => 'Completed',
                'resolved_date' => '11/03/2025',
            ],
        ];

        $technicians = [
            (object)['id' => 1, 'name' => 'Technician A'],
            (object)['id' => 2, 'name' => 'Technician B'],
            (object)['id' => 3, 'name' => 'Technician C'],
        ];

        return view('admin.ticketlist', ['tickets' => $tickets, 'technicians' => $technicians]);
    }

    public function show($id)
    {
        $tickets = [
            (object)[
                'id' => 'TK000001',
                'userid' => 'STUD000001',
                'title' => 'Fan Not Working',
                'category' => 'Room Facilities',
                'description' => 'Fan stops functioning',
                'location' => 'M04 Saujana 04-28B',
                'date' => '05/01/2025',
                'status' => 'Completed',
                'resolved_date' => '06/01/2025',
            ],
            (object)[
                'id' => 'TK000002',
                'userid' => 'STUD000001',
                'title' => 'Light Flickering',
                'category' => 'Electrical & Lighting',
                'description' => 'Main light flickers occasionally.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '11/01/2025',
                'status' => 'Completed',
                'resolved_date' => '13/02/2025',
            ],
            (object)[
                'id' => 'TK000003',
                'userid' => 'STUD000002',
                'title' => 'Slow Wi-Fi Speed',
                'category' => 'Internet Connection',
                'description' => 'Wi-Fi unusually slow at night.',
                'location' => 'M03 Saujana 03-56A',
                'date' => '16/01/2025',
                'status' => 'Cancel',
                'comment' => 'Ticket cancelled as the problem has been resolved.',
                'resolved_date' => '18/01/2025',
            ],
            (object)[
                'id' => 'TK000004',
                'userid' => 'STUD000003',
                'title' => 'Dirty Pantry Area',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Pantry not clean.',
                'location' => 'M03 Saujana Pantry Level 4',
                'date' => '18/01/2025',
                'status' => 'Completed',
                'resolved_date' => '19/01/2025',
            ],
            (object)[
                'id' => 'TK000005',
                'userid' => 'STUD000001',
                'title' => 'Clogged Toilet',
                'category' => 'Toilet & Plumbing',
                'description' => 'Toilet bowl clogged.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '21/01/2025',
                'status' => 'Cancel',
                'comment' => 'Ticket cancelled as the problem has been resolved.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000006',
                'userid' => 'STUD000004',
                'title' => 'Broken Study Table',
                'category' => 'Room Facilities',
                'description' => 'Table leg broken.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '25/01/2025',
                'status' => 'Completed',
                'resolved_date' => '26/01/2025',
            ],
            (object)[
                'id' => 'TK000007',
                'userid' => 'STUD000001',
                'title' => 'Power Socket Not Working',
                'category' => 'Electrical & Lighting',
                'description' => 'Socket suddenly stopped functioning.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '30/01/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000008',
                'userid' => 'STUD000005',
                'title' => 'Frequent Wi-Fi Disconnection',
                'category' => 'Internet Connection',
                'description' => 'Wi-Fi disconnects frequently.',
                'location' => 'M04 Saujana 06-32B',
                'date' => '02/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000009',
                'userid' => 'STUD000006',
                'title' => 'Dusty Corridor',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Corridor not cleaned for days.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '05/02/2025',
                'status' => 'Completed',
                'resolved_date' => '06/02/2025',
            ],
            (object)[
            'id' => 'TK000010',
            'userid' => 'STUD000002',
            'title' => 'Air Conditioner Leaking',
            'category' => 'Room Facilities',
            'description' => 'Water dripping from AC.',
            'location' => 'M03 Saujana 03-56A',
            'date' => '10/02/2025',
            'status' => 'Completed',
            'resolved_date' => '11/02/2025',
            ],
            (object)[
                'id' => 'TK000011',
                'userid' => 'STUD000007',
                'title' => 'Room Light Not Turning On',
                'category' => 'Electrical & Lighting',
                'description' => 'Switch responds but no light.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '12/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000012',
                'userid' => 'STUD000004',
                'title' => 'Intermittent Wi-Fi Drop',
                'category' => 'Internet Connection',
                'description' => 'Disconnects for a few minutes.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '13/02/2025',
                'status' => 'Completed',
                'resolved_date' => '14/02/2025',
            ],
            (object)[
                'id' => 'TK000013',
                'userid' => 'STUD000008',
                'title' => 'Unclean Washroom',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Washroom floor dirty.',
                'location' => 'M03 Saujana 02-12A',
                'date' => '14/02/2025',
                'status' => 'Completed',
                'resolved_date' => '15/02/2025',
            ],
            (object)[
                'id' => 'TK000014',
                'userid' => 'STUD000009',
                'title' => 'Pipe Leakage',
                'category' => 'Toilet & Plumbing',
                'description' => 'Water leaking below sink.',
                'location' => 'M04 Saujana 01-08A',
                'date' => '15/02/2025',
                'status' => 'Cancel',
                'comment' => 'Issue resolved by student.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000015',
                'userid' => 'STUD000002',
                'title' => 'Broken Door Lock',
                'category' => 'Room Facilities',
                'description' => 'Door cannot lock properly.',
                'location' => 'M04 Saujana 04-28B',
                'date' => '17/02/2025',
                'status' => 'Completed',
                'resolved_date' => '18/02/2025',
            ],
            (object)[
                'id' => 'TK000016',
                'userid' => 'STUD000006',
                'title' => 'Corridor Lights Off',
                'category' => 'Electrical & Lighting',
                'description' => 'Whole corridor lights not working.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '18/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000017',
                'userid' => 'STUD000007',
                'title' => 'No Water Supply',
                'category' => 'Toilet & Plumbing',
                'description' => 'Water suddenly stops.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '20/02/2025',
                'status' => 'Completed',
                'resolved_date' => '20/02/2025',
            ],
            (object)[
                'id' => 'TK000018',
                'userid' => 'STUD000003',
                'title' => 'Dirty Laundry Area',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Trash not cleaned for days.',
                'location' => 'M03 Saujana Laundry Level 2',
                'date' => '21/02/2025',
                'status' => 'Completed',
                'resolved_date' => '22/02/2025',
            ],
            (object)[
                'id' => 'TK000019',
                'userid' => 'STUD000005',
                'title' => 'Poor Wi-Fi Signal Strength',
                'category' => 'Internet Connection',
                'description' => 'Signal very weak.',
                'location' => 'M04 Saujana 06-32B',
                'date' => '23/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000020',
                'userid' => 'STUD000002',
                'title' => 'Broken Chair',
                'category' => 'Room Facilities',
                'description' => 'Chair leg snapped.',
                'location' => 'M03 Saujana 03-56A',
                'date' => '25/02/2025',
                'status' => 'Completed',
                'resolved_date' => '26/02/2025',
            ],
            (object)[
                'id' => 'TK000021',
                'userid' => 'STUD000004',
                'title' => 'Light Buzzing Noise',
                'category' => 'Electrical & Lighting',
                'description' => 'Buzzing from ceiling light.',
                'location' => 'M03 Saujana 05-45A',
                'date' => '26/02/2025',
                'status' => 'Completed',
                'resolved_date' => '26/02/2025',
            ],
            (object)[
                'id' => 'TK000022',
                'userid' => 'STUD000009',
                'title' => 'Unpleasant Odour in Toilet',
                'category' => 'Toilet & Plumbing',
                'description' => 'Smell for hours.',
                'location' => 'M04 Saujana 01-08C',
                'date' => '28/02/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000023',
                'userid' => 'STUD000008',
                'title' => 'Wet Corridor',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Water spilled, not cleaned.',
                'location' => 'M03 Saujana Corridor Level 3',
                'date' => '01/03/2025',
                'status' => 'Completed',
                'resolved_date' => '02/03/2025',
            ],
            (object)[
                'id' => 'TK000024',
                'userid' => 'STUD000010',
                'title' => 'Wi-Fi Authentication Error',
                'category' => 'Internet Connection',
                'description' => 'Cannot connect to Wi-Fi.',
                'location' => 'M04 Saujana 08-11A',
                'date' => '03/03/2025',
                'status' => 'Cancel',
                'comment' => 'Duplicate ticket.',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000025',
                'userid' => 'STUD000006',
                'title' => 'Dusty Cupboard',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Cupboard full of dust.',
                'location' => 'M04 Saujana 10-24B',
                'date' => '04/03/2025',
                'status' => 'Completed',
                'resolved_date' => '05/03/2025',
            ],
            (object)[
                'id' => 'TK000026',
                'userid' => 'STUD000003',
                'title' => 'Loose Water Tap',
                'category' => 'Toilet & Plumbing',
                'description' => 'Tap wiggles when used.',
                'location' => 'M03 Saujana 04-27A',
                'date' => '05/03/2025',
                'status' => 'Completed',
                'resolved_date' => '06/03/2025',
            ],
            (object)[
                'id' => 'TK000027',
                'userid' => 'STUD000010',
                'title' => 'Wall Paint Peeling Off',
                'category' => 'Room Facilities',
                'description' => 'Paint falling from wall.',
                'location' => 'M04 Saujana 08-11A',
                'date' => '07/03/2025',
                'status' => 'Pending',
                'resolved_date' => '',
            ],
            (object)[
                'id' => 'TK000028',
                'userid' => 'STUD000007',
                'title' => 'Light Switch Hot',
                'category' => 'Electrical & Lighting',
                'description' => 'Switch becomes hot.',
                'location' => 'M04 Saujana 07-21B',
                'date' => '08/03/2025',
                'status' => 'Completed',
                'resolved_date' => '09/03/2025',
            ],
            (object)[
                'id' => 'TK000029',
                'userid' => 'STUD000010',
                'title' => 'Dirty Pantry Sink',
                'category' => 'Cleanliness & Maintenance',
                'description' => 'Sink full of leftover food.',
                'location' => 'M03 Saujana Pantry Level 2',
                'date' => '10/03/2025',
                'status' => 'Completed',
                'resolved_date' => '11/03/2025',
            ],

        ];

        $ticket = collect($tickets)->firstWhere('id', $id);

        if (!$ticket) {
            abort(404, 'Ticket not found');
        }

        $technicians = [
            (object)['id' => 1, 'name' => 'Technician A'],
            (object)['id' => 2, 'name' => 'Technician B'],
            (object)['id' => 3, 'name' => 'Technician C'],
        ];

        return view('admin.ticketdetails', ['ticket' => $ticket, 'technicians' => $technicians]);
    }

    public function assignTechnician(Request $request)
    {
        $ticketId = $request->ticket_id;
        $technicianId = $request->technician_id;

        // Here you would update DB to assign technician
        // For now, just flash success
        return redirect()->back()->with('success', 'Technician assigned successfully!');
    }
}
